common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from textpage import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("textpage/", include('textpage.urls')),
    path("qna/", include('qna.urls')),
    path("common/", include('common.urls')),
    path("", include('mainpage.urls')),
]

mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.index, name='index'),
    path('permissionerror/', views.permissionerror, name='permissionerror')
]

qna/urls.py
from django.urls import path
from . import views

app_name = 'qna'

urlpatterns = [
    path('', views.index, name='index'),
    path('qna/create/', views.qna_create, name='qna_create'),
]

textpage/urls.py
from django.urls import path
from . import views

app_name = 'textpage'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:text_id>/', views.detail, name='detail'),
    path('comment/create/<int:text_id>/', views.comment_create, name='comment_create'),
    path('text/goodvote/<int:text_id>/', views.text_goodvote, name='text_goodvote'),
    path('text/badvote/<int:text_id>/', views.text_badvote, name='text_badvote'),
    path('text/create/', views.text_create, name='text_create'),
]

common/models.py
from django.db import models

# Create your models here.

qna/models.py
from django.db import models

class QnA(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

textpage/models.py
from django.db import models
from django.contrib.auth.models import User


class Text(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='author_text')
    goodvote = models.ManyToManyField(User, related_name='text_goodvote')
    badvote = models.ManyToManyField(User, related_name='text_badvote')

    def __str__(self):
        return self.subject


class Comment(models.Model):
    texts = models.ForeignKey(Text, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

qna/forms.py
from django import forms
from .models import QnA


class QnaForm(forms.ModelForm):
    class Meta:
        model = QnA
        fields = ['subject', 'content']

textpage/forms.py
from django import forms
from textpage.models import Text, Comment


class TextForm(forms.ModelForm):
    class Meta:
        model = Text
        fields = ['subject', 'content']
        labels = {
            'subject' : '글 제목',
            'content': '글 내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('common:login')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

mainpage/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'mainpage/main.html')


def permissionerror(request):
    return render(request, '403.html')

qna/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import QnA
from django.utils import timezone
from .forms import QnaForm

def index(request):
    text_list = QnA.objects.order_by('-create_date')
    content = {'text_list' : text_list}

    return render(request, 'qna/qna_list.html', content)

def qna_create(request):
    if request.method == 'POST':
        form = QnaForm(request.POST)
        if form.is_valid():
            t = form.save(commit=False)
            t.create_date = timezone.now()
            t.save()
            return redirect('qna:index')
    else:
         form = QnaForm()
    context = {'form':form}
    return render(request, 'qna/qna_form.html', context)

textpage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Text, Comment
from django.utils import timezone
from django.contrib import messages
from .forms import TextForm, CommentForm
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.http import HttpResponseNotAllowed
from django.core.paginator import Paginator

def comment_group_check(user):
    return "comment_allow" in user.groups.all()

def texts_group_check(user):
    return "texts_allow" in user.groups.all()

def index(request):
    page = request.GET.get('page', '1')
    text_list = Text.objects.order_by('-create_date')
    paginator = Paginator(text_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    content = {'text_list': page_obj}
    return render(request, 'textpage/textpage_list.html', content)

def detail(request, text_id):
    text = get_object_or_404(Text, pk=text_id)
    content = {'text' : text}
    return render(request, 'textpage/text_detail.html', content)

@login_required(login_url='common:login')
def comment_create(request, text_id):
    text = get_object_or_404(Text, pk=text_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.texts = text
            answer.author = request.user
            answer.save()
            return redirect('textpage:detail', text_id=text.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'text': text, 'form': form}
    return render(request, 'textpage/text_detail.html', context)

@login_required(login_url='common:login')
def text_create(request):
    if request.method == 'POST':
        form = TextForm(request.POST)
        if form.is_valid():
            t = form.save(commit=False)
            t.author = request.user
            t.create_date = timezone.now()
            t.save()
            return redirect('textpage:index')
    else:
         form = TextForm()
    context = {'form':form}
    return render(request, 'textpage/text_form.html', context)

@login_required(login_url='common:login')
def text_goodvote(request, text_id):
    question = get_object_or_404(Text, pk=text_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        Text.objects.get(id=text_id).goodvote.add(request.user)
    return redirect('textpage:detail', text_id=question.id)

@login_required(login_url='common:login')
def text_badvote(request, text_id):
    question = get_object_or_404(Text, pk=text_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        Text.objects.get(id=text_id).badvote.add(request.user)
    return redirect('textpage:detail', text_id=question.id)

templates/common/login.html
{% extends 'text_base.html' %}
{% block content %}
<div class="container my-3">
  <form method="post" action="{% url 'common:login' %}">
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ next }}">
      {% include "form_errors.html" %}
      <div class="mb-3">
          <label for="username">사용자ID</label>
          <input type="text" class="form-control" name="username" id="username"
                 value="{{ form.username.value|default_if_none:'' }}">
      </div>
      <div class="mb-3">
          <label for="password">비밀번호</label>
          <input type="password" class="form-control" name="password" id="password"
                 value="{{ form.password.value|default_if_none:'' }}">
      </div>
      <button type="submit" class="btn btn-primary">로그인</button>
  </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "text_base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름 (본명을 적어주세요, 본명이 아니라면 차단됩니다)</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일 (학교 이메일이 아니거나 본명과 일치하지 않는다면 차단됩니다.)</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/mainpage/main.html
{% extends 'text_base.html' %}
{% block content %}
<blockquote>
  이 사이트는 그냥 만든 사이트 입니다.<br>
  학교에서 DC를 정직하게 할 수 없기에<br>
  <b>학교</b>에서 <b>DC</b>를 갈 수 없다면<br>
  <i><b>DC</b>를 <b>학교</b>로</i> 오게 해 보고 싶었습니다<br><br>
  이 사이트는 <b>모바일, 데스크탑, 크롬북(!)</b> 등등 다양한 곳에서 작동합니다<br>
  선을 넘지 않는 이상 <b>자유롭게</b> 사용할 수 있는 공간이니 마음껏 즐겨주세요<br>
  아직 <b>개발 과정</b>이니 그 점 유의하시길 바랍니다<br>
  감사합니다!<br><br>
  - ICARUS 노예 -
</blockquote>
<p><small>지금 안들어가지는 곳들은 그냥 구현이 안된 곳입니다..ㅋㅋ</small></p>
<p>..</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>뭐야 왜 내려봐요...?</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>아무것도 없어요... 저리 가요</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>진짠데...</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p><a href="#">이거라도 드릴께요..</a></p>
{% endblock %}

templates/qna/qna_form.html
{% extends 'text_base.html' %}
{% block content %}
<div class="container my-3">
  <h5>질문 등록</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primart">저장하기</button>
  </form>
</div>
{% endblock %}

templates/qna/qna_list.html
{% extends 'text_base.html' %}
{% block content %}
  <div>
    <p><a class="btn btn-outline-dark" href="{% url 'qna:qna_create' %}" role="button">글 작성</a></p>
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if text_list %}
        {% for question in text_list %}
        <tr>
            <td>{{ forloop.revcounter }}</td>
            <td>
                {{ question.subject }}
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
  </div>
{% endblock %}

templates/text_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,  inital-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>경북과고 DC</title>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg" style="background-color: #95db84;">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'mainpage:index' %}">
            <h4>
              <img src="{% static 'image.svg' %}" alt="Logo" width="60" height="60" class="d-inline-block align-text-center">
            </h4>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'textpage:index' %}"><b>게시판</b></a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'qna:index' %}"><b>문의사항</b></a>
              </li>
            </ul>
            {% if not user.is_authenticated %}
              <a class="nav-link" href="{% url 'common:signup' %}"><b>회원가입</b></a>
            {% endif %}
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
            {% else %}
            <a class="nav-link" href="{% url 'common:login' %}"><b>로그인</b></a>
            {% endif %}
            &nbsp;&nbsp;&nbsp;
          </div>
        </div>
      </nav>
      <script src="{% static 'bootstrap.min.js' %}"></script>
    </header>

    <main>
      <div class="container">
        <p></p>
        {% block content %}
        {% endblock %}
        <p></p>
      </div>
    </main>

    <footer>
      <nav class="navbar navbar-expand sticky-bottom" style="background-color: #606060;">
        <div class="container-fluid">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">사이트 정보</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">개인정보처리방침</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">연락처</a>
            </li>
          </ul>
        </div>
      </nav>
    </footer>
  </body>
</html>

templates/textpage/text_detail.html
{% extends 'text_base.html' %}
{% block content %}
  <h2 class="border-bottom py-2">{{ text.subject }}</h2>
  <div class="container my-3">
    <div class="card my-3">
      <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">
          {{ text.content }}
        </div>
        <div class="d-flex justify-content-end">
          <div class="badge bg-secondary">
            {{ text.create_date }}
          </div>
        </div>
        <div class="my-3">
          <a href="{% url 'textpage:text_goodvote' text.id %}" class="btn btn-sm btn-outline-secondary">
            추천
            <span class="badge rounded-pill bg-success">{{text.goodvote.count}}</span>
          </a>
          <a href="{% url 'textpage:text_badvote' text.id %}" class="btn btn-sm btn-outline-secondary">
            비추천
            <span class="badge rounded-pill bg-danger">{{text.badvote.count}}</span>
          </a>
        </div>
      </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
      {{ text.comment_set.count }}개의 답변이 있습니다.
    </h5>
    {% for Text in text.comment_set.all %}
    <div class="card my-3">
      <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">
          {{ Text.content }}
        </div>
        <div class="d-flex justify-content-end">
          <div class="badge bg-secondary">
            {{ Text.create_date }}
          </div>
        </div>
      </div>
    </div>
    {% endfor %}

    <h5 class="border-bottom">댓글 작성</h5>
    <form action="{% url 'textpage:comment_create' text.id %}" method="post" class="my-3">
      {% csrf_token %}
      <!-- 오류표시 Start -->
      {% if form.errors %}
      <div class="alert alert-danger" role="alert">
          {% for field in form %}
          {% if field.errors %}
          <div>
              <strong>{{ field.label }}</strong>
              {{ field.errors }}
          </div>
          {% endif %}
          {% endfor %}
      </div>
      {% endif %}
      <!-- 오류표시 End -->
      <div class="form-group">
        <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
      </div>
      <h1>  </h1>
      <input {% if not user.is_authenticated %}disabled{% endif %} type="submit" class="btn btn-outline-dark" value="댓글 등록">
    </form>
  </div>
{% endblock %}

templates/textpage/text_form.html
{% extends 'text_base.html' %}
{% block content %}
<div class="container my-3">
  <h5>글 등록</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    <!-- 오류표시 Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        {% for field in form %}
        {% if field.errors %}
        <div>
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% endif %}
    <!-- 오류표시 End -->
    <div class="mb-3">
        <label for="subject" class="form-label">제목</label>
        <input type="text" class="form-control" name="subject" id="subject"
               value="{{ form.subject.value|default_if_none:'' }}">
    </div>
    <div class="mb-3">
        <label for="content" class="form-label">내용</label>
        <textarea class="form-control" name="content"
                  id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <button type="submit" class="btn btn-outline-dark">저장하기</button>
  </form>
</div>
{% endblock %}

templates/textpage/textpage_list.html
{% extends 'text_base.html' %}
{% block content %}
  <div>
    <p><a class="btn btn-outline-dark" href="{% url 'textpage:text_create' %}" role="button">글 작성</a></p>
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
            <th>추천수</th>
        </tr>
        </thead>
        <tbody>
        {% if text_list %}
        {% for question in text_list %}
        <tr>
            <td>{{ question.id }}</td>
            <td>
                <a class="nav-link" href="{% url 'textpage:detail' question.id %}">
                    {{ question.subject }}
                    {% if question.comment_set.count > 0 %}
                    <span class="text-danger small ml-2">
                        [{{ question.comment_set.count}}]
                    </span>
                    {% endif %}
                </a>
                
            </td>
            <td>
                {{ question.create_date }}
            </td>
            <td>
                {{ question.goodvote.count }} / {{ question.badvote.count }}
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</table>
<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if text_list.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ text_list.previous_page_number }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in text_list.paginator.page_range %}
    {% if page_number == text_list.number %}
    <li class="page-item active" aria-current="page">
        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if text_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ text_list.next_page_number }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
</ul>
<!-- 페이징처리 끝 -->
  </div>
{% endblock %}

templates/ztest_html/gg.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8">
    <title>경북과고 DC</title>
  </head>

  <body>
    <header>
      <div id="logo">
        <a href="https://kbsc-dc.run.goorm.app"><h1>경북과고 DC</h1></a>
      </div>
      <nav id="topmenu">
        <li><a href="https://kbsc-dc.run.goorm.app/textpage">글 지랄</a></li>
        <li><a href="#">문의하기</a></li>
        <li><a href="https://kbsc-dc.run.goorm.app/admin">관리자</a></li>
      </nav>
    </header>

    <main>
      
    </main>

    <footer>
      <nav id="bottommenu">
        <li><a href="#">사이트 소개</a></li>
        <li><a href="#">개인정보처리방침</a></li>
        <li><a href="#">그 외 잡것들</a></li>
      </nav>
    </footer>
  </body>
</html>